INSERT INTO public.stations (name) VALUES ('Москва');
INSERT INTO public.stations (name) VALUES ('Владивосток');
INSERT INTO public.stations (name) VALUES ('Оренбург');
INSERT INTO public.stations (name) VALUES ('Санкт-Петербург');
INSERT INTO public.stations (name) VALUES ('Тосно');
INSERT INTO public.stations (name) VALUES ('Чудово');
INSERT INTO public.stations (name) VALUES ('Окуловка');
INSERT INTO public.stations (name) VALUES ('Угловка');
INSERT INTO public.stations (name) VALUES ('Бологое');
INSERT INTO public.stations (name) VALUES ('Тверь');
INSERT INTO public.stations (name) VALUES ('Решетниково');
INSERT INTO public.stations (name) VALUES ('Поварово');
INSERT INTO public.stations (name) VALUES ('Вышний Волочёк');
INSERT INTO public.stations (name) VALUES ('Малая Вишера');
INSERT INTO public.stations (name) VALUES ('Спирово');
INSERT INTO public.stations (name) VALUES ('Лихославль');
INSERT INTO public.stations (name) VALUES ('Тула');
INSERT INTO public.stations (name) VALUES ('Мценск');
INSERT INTO public.stations (name) VALUES ('Орёл');
INSERT INTO public.stations (name) VALUES ('Поныри');
INSERT INTO public.stations (name) VALUES ('Курск');
INSERT INTO public.stations (name) VALUES ('Солнцево');
INSERT INTO public.stations (name) VALUES ('Ржава');
INSERT INTO public.stations (name) VALUES ('Белгород');

INSERT INTO public.routes (route_number, name, schedule_pattern) VALUES ('279А', 'Санкт-Петербург → Москва', 'WEEK;1;5');
INSERT INTO public.routes (route_number, name, schedule_pattern) VALUES ('128А', 'Москва → Санкт-Петербург', 'WEEK;2;4');
INSERT INTO public.routes (route_number, name, schedule_pattern) VALUES ('119А', 'Санкт-Петербург → Белгород', '');
INSERT INTO public.routes (route_number, name, schedule_pattern) VALUES ('120В', 'Белгород → Санкт-Петербург', '');

INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (1, 4, null, 2400, 0);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (1, 9, 15120, 17220, 1);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (1, 13, 19320, 19380, 2);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (1, 10, 27000, 27120, 3);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (1, 1, 36420, null, 4);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (2, 1, null, 5100, 0);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (2, 10, 11460, 11580, 1);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (2, 13, 15900, 16020, 2);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (2, 9, 17820, 18840, 3);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (2, 7, 21720, 21840, 4);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (2, 4, 40260, null, 5);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 4, null, 660, 0);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 14, 7680, 7740, 1);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 7, 11160, 11280, 2);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 9, 13980, 16200, 3);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 13, 18300, 18420, 4);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 15, 19800, 19860, 5);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 16, 21600, 21720, 6);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 10, 23340, 23460, 7);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 1, 35100, 36720, 8);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 18, 46080, 47580, 9);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 19, 53220, 53340, 10);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 20, 55800, 59100, 11);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 21, 62700, 62820, 12);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 22, 65460, 67080, 13);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 23, 69900, 70020, 14);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (3, 24, 75240, null, 15);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 24, null, 34800, 0);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 23, 40320, 40440, 1);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 22, 43320, 44940, 2);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 21, 48120, 48240, 3);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 20, 51600, 54900, 4);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 19, 57480, 57600, 5);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 18, 63060, 64860, 6);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 1, 76440, 78120, 7);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 10, 87360, 87480, 8);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 16, 89220, 91200, 9);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 15, 93000, 93060, 10);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 13, 94500, 95040, 11);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 9, 96780, 96900, 12);
INSERT INTO public.route_station (route_id, station_id, arrival_time, departure_time, index_in_route) VALUES (4, 4, 113400, null, 13);

INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-22', false, 1);
INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-22', false, 2);
INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-23', false, 1);
INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-23', false, 2);
INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-24', false, 1);
INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-24', false, 2);
INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-25', false, 1);
INSERT INTO public.trips (start_date, canceled, route_id) VALUES ('2019-11-25', false, 2);

INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (1, 4, null, '2019-11-22 00:40:00.000000', 1);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (1, 9, '2019-11-22 04:12:00.000000', '2019-11-22 04:47:00.000000', 2);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (1, 13, '2019-11-22 05:22:00.000000', '2019-11-22 05:23:00.000000', 3);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (1, 10, '2019-11-22 07:30:00.000000', '2019-11-22 07:32:00.000000', 4);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (1, 1, '2019-11-22 10:07:00.000000', null, 5);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (2, 1, null, '2019-11-22 01:25:00.000000', 1);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (2, 10, '2019-11-22 03:11:00.000000', '2019-11-22 03:13:00.000000', 2);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (2, 13, '2019-11-22 04:25:00.000000', '2019-11-22 04:27:00.000000', 3);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (2, 9, '2019-11-22 04:57:00.000000', '2019-11-22 05:14:00.000000', 4);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (2, 7, '2019-11-22 06:02:00.000000', '2019-11-22 06:04:00.000000', 5);
INSERT INTO public.trip_station (trip_id, station_id, arrival_time, departure_time, index_in_trip) VALUES (2, 4, '2019-11-22 11:11:00.000000', null, 6);

INSERT INTO public.passengers (first_name, last_name, birth_date, gender) VALUES ('Петр', 'Иванов', '1950-01-01', 'M');
INSERT INTO public.passengers (first_name, last_name, birth_date, gender) VALUES ('Иван', 'Петров', '1950-01-01', 'M');
INSERT INTO public.passengers (first_name, last_name, birth_date, gender) VALUES ('Александр', 'Жданов', '1950-01-01', 'M');
INSERT INTO public.passengers (first_name, last_name, birth_date, gender) VALUES ('Василий', 'Теркин', '1950-01-01', 'M');
INSERT INTO public.passengers (first_name, last_name, birth_date, gender) VALUES ('Александр', 'Цекало', '1950-01-01', 'M');
INSERT INTO public.passengers (first_name, last_name, birth_date, gender) VALUES ('Олег', 'Газманов', '1950-01-01', 'M');

INSERT INTO public.tickets (passenger_id, trip_id, start_station_id, end_station_id, wagon_number, seat_number, price) VALUES (1, 1, 4, 1, 1, 1, 5000);
INSERT INTO public.tickets (passenger_id, trip_id, start_station_id, end_station_id, wagon_number, seat_number, price) VALUES (2, 1, 4, 1, 1, 2, 5000);